import esbuild from 'esbuild';
import { appendFileSync, readFileSync } from 'node:fs';
import { builtinModules } from 'node:module';
import process from 'process';

// Shared with release-check.mjs, which re-checks the same threshold against an
// already-built main.js — both read this key so the two checks can't drift apart.
// Obsidian loads every enabled plugin's `main.js` at vault startup — a size
// regression is a user-facing cost, not just a build metric. Bump this in
// package.json if the plugin legitimately grows, but bump it deliberately.
const { mainJsBudgetBytes: MAIN_JS_BUDGET_BYTES } = JSON.parse(
  readFileSync('package.json', 'utf8'),
).release;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const args = process.argv.slice(2);
const prod = args.includes('production');
const analyze = args.includes('analyze');

// Obsidian strips inline source maps from dev builds unless main.js ends with
// this exact marker comment: https://forum.obsidian.md/t/source-map-trimming-in-dev-builds/87612
const nosourcemapPlugin = {
  name: 'nosourcemap-marker',
  setup(build) {
    build.onEnd(() => {
      if (!prod) {
        appendFileSync('main.js', '\n/* nosourcemap */');
      }
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
  ],
  format: 'cjs',
  target: 'es2021',
  logLevel: analyze ? 'silent' : 'info',
  sourcemap: prod ? false : 'inline',
  drop: ['debugger'],
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
  metafile: prod || analyze,
  plugins: [nosourcemapPlugin],
});

if (prod) {
  const result = await context.rebuild();
  if (analyze) {
    console.info(await esbuild.analyzeMetafile(result.metafile, { verbose: false }));
  }
  checkSizeBudget(result.metafile);
  process.exit(0);
} else {
  await context.watch();
}

function checkSizeBudget(metafile) {
  const bytes = Object.values(metafile.outputs).reduce((total, output) => total + output.bytes, 0);

  if (bytes > MAIN_JS_BUDGET_BYTES) {
    console.error(
      `main.js is ${(bytes / 1024).toFixed(1)} KB, over the ${(MAIN_JS_BUDGET_BYTES / 1024).toFixed(0)} KB budget in esbuild.config.mjs. ` +
        'Check for an accidentally-bundled dependency, or raise the budget deliberately.',
    );
    process.exit(1);
  }
}
